# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    outputs:
      run_test_step: ${{ steps.check_commits.outputs.run_test_step }}
    steps:
      - name: Check for New Commits
        id: check_commits
        uses: actions/github-script@v6
        with:
          script: |
            const twoMinutesAgo = new Date(Date.now() - 2 * 60 * 1000); // 2 minutes in milliseconds
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              since: twoMinutesAgo.toISOString(),
            });
            if (commits.length === 0) {
              console.log("No commits in the last 2 minutes. Ending workflow execution.");
              core.setOutput("run_test_step", "false");
              return; // Soft exit: Ends the script without an error.
            } else {
              console.log(`Found ${commits.length} commits in the last 2 minutes.`);
              core.setOutput("run_test_step", "true");
              // Print commit details...
            }
          result-encoding: string
      
      - name: Test Step
        if: steps.check_commits.outputs.run_test_step == 'true'
        run: echo "This step will only run if the 'Check for New Commits' step found new commits."
